# Generated by Django 5.2.8 on 2026-01-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_number', models.CharField(max_length=50, unique=True)),
                ('device_mac', models.CharField(max_length=17, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('status', models.CharField(choices=[('online', 'online'), ('warning', 'warning'), ('offline', 'offline')], default='online', max_length=10)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
