# Generated by Django 5.2.8 on 2026-01-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.TextField()),
                ('src_mac', models.TextField()),
                ('time', models.DateTimeField()),
                ('rssi', models.IntegerField()),
            ],
        ),
    ]
