# Generated by Django 5.2.8 on 2026-02-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_devicelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='분석 날짜')),
                ('target_hour', models.IntegerField(verbose_name='분석 시간')),
                ('current_stay_count', models.IntegerField(default=0, verbose_name='현재 총 체류 인원')),
                ('current_density', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='현재 총 밀집도')),
                ('today_visitor_count', models.IntegerField(default=0, verbose_name='오늘 누적 방문 인원')),
                ('period_visitor_count', models.IntegerField(default=0, verbose_name='특정 기간 내 누적 방문 인원')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '홈 장치 상태',
                'verbose_name_plural': '홈 장치 상태 목록',
                'db_table': 'home_device_status',
                'constraints': [models.UniqueConstraint(fields=('target_date', 'target_hour'), name='unique_date_hour')],
            },
        ),
    ]
