# Generated by Django 5.2.8 on 2026-02-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homedevicestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homedevicestatus",
            name="current_density",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="현재 총 밀집도",
            ),
        ),
    ]
