# Generated by Django 5.2.8 on 2026-02-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homedevicestatus_current_density'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homedevicestatus',
            name='unique_date_hour',
        ),
        migrations.AddField(
            model_name='homedevicestatus',
            name='device_mac',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='장치 MAC 주소'),
        ),
        migrations.AddConstraint(
            model_name='homedevicestatus',
            constraint=models.UniqueConstraint(fields=('device_mac', 'target_date', 'target_hour'), name='unique_device_date_hour'),
        ),
    ]
