# Generated by Django 5.2.8 on 2026-02-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homedevicestatus_unique_date_hour_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeDeviceStatus',
            new_name='DeviceStatus',
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='devicelog',
            name='mac',
        ),
        migrations.AddField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(blank=True, db_column='device_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='home.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_mac',
            field=models.CharField(db_index=True, max_length=17, unique=True, verbose_name='디바이스 MAC 주소'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='기기 번호'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='src_mac',
            field=models.CharField(db_index=True, max_length=17, verbose_name='소스 MAC 주소'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='time',
            field=models.DateTimeField(db_index=True, verbose_name='로그 시간'),
        ),
        migrations.AlterModelTable(
            name='device',
            table='home_device',
        ),
        migrations.AlterModelTable(
            name='devicelog',
            table='home_devicelog',
        ),
        migrations.RemoveConstraint(
            model_name='devicestatus',
            name='unique_device_date_hour',
        ),
        migrations.RemoveField(
            model_name='devicestatus',
            name='device_mac',
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='target_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='current_density',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='device',
            field=models.ForeignKey(db_column='device_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='home.device'),
        ),
    ]
