# Generated by Django 5.2.8 on 2026-02-11 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_devicestatus_delete_homedevicestatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestatus',
            options={},
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='current_stay_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='device',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='home.device'),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='period_visitor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='target_hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='today_visitor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='devicestatus',
            constraint=models.UniqueConstraint(fields=('device', 'target_date', 'target_hour'), name='unique_device_time_slot'),
        ),
    ]
