# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_devicestatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='target_minute',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.RemoveConstraint(
            model_name='devicestatus',
            name='unique_device_time_slot',
        ),
        migrations.AddConstraint(
            model_name='devicestatus',
            constraint=models.UniqueConstraint(fields=('device', 'target_date', 'target_hour', 'target_minute'), name='unique_device_time_slot'),
        ),
    ]
